= CH 4

== Bubble & Shell Sort

They are in the `sorting` module, tested by unit-tests.

== Sorting Text

`Go` can compare strings lexicographically, therefore no additional `cmp` method is needed.
Also, `Go` can have an array of stringsand we just exchange pointers.

However, I think the idea of having one long array of text and array of pointers is interesting. That's why I implemented it as in the original

I only hesitate about implementation of `exachange` function. As in `Go` integers are copied, I have to pass `linepos` and indexes there.
Original is a bit different.

.inmemsort
----
$ go build  sorttext.go  io.go

$ ./sorttext
zzz
aaa
nnn
^D
aaa
nnn
zzz
----


== Quicksort

There is also an implementation of `quicksort` in `sortring/sort.go` tested by unit tests.

.inmemsort with quick
----
$ go build  sorttext.go  io.go  && ./sorttext
zzz
aaa
nnn
^D
aaa
nnn
zzz
----

== Sorting Big Files

Very interesting approach with heap, see `reheap`.

.externalsort
----
 go build externalsort.go io.go qsort.go && cat bigfile | ./externalsort
# it indeed sorts
----